# Generated by Django 4.0.5 on 2022-06-04 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_usdrub'),
    ]

    operations = [
        migrations.CreateModel(
            name='USDRUB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('min', models.IntegerField()),
                ('max', models.IntegerField()),
            ],
        ),
    ]
