# Generated by Django 4.0.5 on 2022-06-04 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_audusd_max_alter_audusd_min_alter_btcusd_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('min', models.FloatField()),
                ('max', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyPairs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_pair', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='AUDUSD',
        ),
        migrations.DeleteModel(
            name='BTCUSD',
        ),
        migrations.DeleteModel(
            name='EURAUD',
        ),
        migrations.DeleteModel(
            name='EURCHF',
        ),
        migrations.DeleteModel(
            name='EURGBP',
        ),
        migrations.DeleteModel(
            name='EURJPY',
        ),
        migrations.DeleteModel(
            name='EURRUB',
        ),
        migrations.DeleteModel(
            name='EURUSD',
        ),
        migrations.DeleteModel(
            name='GBPUSD',
        ),
        migrations.DeleteModel(
            name='JPYRUB',
        ),
        migrations.DeleteModel(
            name='NZDUSD',
        ),
        migrations.DeleteModel(
            name='USDCAD',
        ),
        migrations.DeleteModel(
            name='USDCHF',
        ),
        migrations.DeleteModel(
            name='USDJPY',
        ),
        migrations.DeleteModel(
            name='USDRUB',
        ),
        migrations.AddField(
            model_name='currencypair',
            name='currency_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_pairs', to='api.currencypairs'),
        ),
    ]
